### PR TITLE
Returns GPU count

### PR DESCRIPTION
**Pull request by gerardo8a**
This will add number of gpus to be labeled in the node. 

I couldn't run the tests because I'm using Mac OS so not sure how to run them, I hope this is the only thing that needs to be done, if not let me know so I can add whatever is needed.

Thanks

### CODE REVIEW

**Comment by Ethyling** [comment]
Hey, thank you for your PR! Can you do it on https://gitlab.com/nvidia/kubernetes/gpu-feature-discovery? The github repository is only a mirror AFAIK. You may need to update the README too. Thank you

**Comment by RenaudWasTaken** [comment]
Could you also sign-off your commits :) ?
https://github.com/NVIDIA/gpu-feature-discovery/blob/master/CONTRIBUTING.md

**Comment by gerardo8a** [comment]
will do! thanks

**Comment by gerardo8a** [comment]
Closing PR on behalf of https://gitlab.com/nvidia/kubernetes/gpu-feature-discovery/-/merge_requests/13

**Pull request closed without merging**
